- name: Deploy ACM on OCP Cluster
  import_tasks: deploy_acm.yml
  when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- name: Deploy ACM on rhacm SNO Cluster
  import_tasks: deploy_acm_sno.yml
  when: ocp4_aio_deploy_type == 'sno'